/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogodavelhaframe;

import java.awt.Color;
import static java.lang.System.exit;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Principal extends javax.swing.JFrame {

    int qtde;
    int jogador;
    int mat[][] = new int[3][3];
    JButton b[] = new JButton[9];
    String ganhador;
    String jogador1;
    String jogador2;
    int placar1 = 0;
    int placar2 = 0;

    /**
     * Creates new form Principal
     */
    public Principal() {
        JOptionPane.showMessageDialog(null, "Bem Vindo ao Jogo da Velha");
        initComponents();
        tabuleiroPainel.setVisible(false);
        JBu_02.setVisible(true);
        qtde = 1;
        jogador = 1;
        b[0] = bt_0;
        b[1] = bt_1;
        b[2] = bt_2;
        b[3] = bt_3;
        b[4] = bt_4;
        b[5] = bt_5;
        b[6] = bt_6;
        b[7] = bt_7;
        b[8] = bt_8;
    }

    public void jogada(JButton b, int x, int y) {
        b.setEnabled(false);
        if (jogador == 1) {
            mat[x][y] = 1;
            b.setText("x");
            jogador = 2;
            ganhador = jogador1;
            checarjogada(1);
        } else {
            mat[x][y] = 2;
            b.setText("o");
            jogador = 1;
            ganhador = jogador2;
            checarjogada(2);
        }
        qtde++;

    }

    public void checarjogada(int x) {
        if (vitoria(x) == true) {
            JOptionPane.showMessageDialog(null, "jogador: " + ganhador + " " + "Venceu! ");

            if (ganhador == jogador1) {
                placar1 = placar1 + 1;
            }
            if (ganhador == jogador2) {
                placar2 = placar2 + 1;
            }
            
            limpar();
        }
        placarJ1.setText(Integer.toString(placar1));
        placarJ2.setText(Integer.toString(placar2));
        
    }

    public boolean vitoria(int x) {

        for (int i = 0; i < mat.length; i++) {
            if (mat[i][0] == x && mat[i][1] == x && mat[i][2] == x) {
                return true;
            }
            if (mat[0][i] == x && mat[1][i] == x && mat[2][i] == x) {
                return true;
            }
        }
        if (mat[0][0] == x && mat[1][1] == x && mat[2][2] == x) {
            return true;
        }
        if (mat[0][2] == x && mat[1][1] == x && mat[2][0] == x) {
            return true;
        }
        
        return false;
        
    }

    public void fimjogo() {
        int i;
        for (i = 0; i < 9; i++) {
            b[i].setEnabled(false);
        }
        
    }

    public void limpar() {
        for (int i = 0; i < 9; i++) {
            b[i].setEnabled(true);
            b[i].setText("");
        }
        for (int x = 0; x < 3; x++) {
            for (int y = 0; y < 3; y++) {
                mat[x][y] = 0;
            }
        }
        jogador = 1;
        ganhador = "";
    }
    public void limparTabuleiro() {
        for (int i = 0; i < 9; i++) {
            b[i].setEnabled(true);
            b[i].setText("");
        }
        for (int x = 0; x < 3; x++) {
            for (int y = 0; y < 3; y++) {
                mat[x][y] = 0;
            }
        }
    }

    public void limparplacar() {
        for (int i = 0; i < 9; i++) {
            b[i].setEnabled(true);
            b[i].setText("");
        }
        for (int x = 0; x < 3; x++) {
            for (int y = 0; y < 3; y++) {
                mat[x][y] = 0;
            }
        }
        jogador = 1;
        ganhador = "";
        placar1 = 0;
        placar2 = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JBu_02 = new javax.swing.JButton();
        tabuleiroPainel = new javax.swing.JPanel();
        bt_0 = new javax.swing.JButton();
        lblVelha = new javax.swing.JLabel();
        bt_1 = new javax.swing.JButton();
        bt_5 = new javax.swing.JButton();
        bt_7 = new javax.swing.JButton();
        bt_3 = new javax.swing.JButton();
        bt_8 = new javax.swing.JButton();
        bt_6 = new javax.swing.JButton();
        bt_2 = new javax.swing.JButton();
        bt_4 = new javax.swing.JButton();
        nomeJ1 = new javax.swing.JLabel();
        nomeJ2 = new javax.swing.JLabel();
        placarJ1 = new javax.swing.JLabel();
        placarJ2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo Da Velha");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.black);
        setResizable(false);

        JBu_02.setBackground(new java.awt.Color(153, 51, 255));
        JBu_02.setFont(new java.awt.Font("Stencil", 1, 12)); // NOI18N
        JBu_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogodavelhaframe/imagens/control_play.png"))); // NOI18N
        JBu_02.setText("Começar Jogo!");
        JBu_02.setToolTipText("");
        JBu_02.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        JBu_02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBu_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBu_02ActionPerformed(evt);
            }
        });

        tabuleiroPainel.setBackground(new java.awt.Color(102, 102, 102));

        bt_0.setBackground(new java.awt.Color(153, 51, 255));
        bt_0.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        bt_0.setForeground(new java.awt.Color(255, 255, 0));
        bt_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_0.setPreferredSize(new java.awt.Dimension(75, 75));
        bt_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_0ActionPerformed(evt);
            }
        });

        lblVelha.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Nova Pasta\\velha.png.png")); // NOI18N

        bt_1.setBackground(new java.awt.Color(153, 51, 255));
        bt_1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        bt_1.setForeground(new java.awt.Color(255, 255, 0));
        bt_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_1.setPreferredSize(new java.awt.Dimension(75, 75));
        bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1ActionPerformed(evt);
            }
        });

        bt_5.setBackground(new java.awt.Color(153, 51, 255));
        bt_5.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        bt_5.setForeground(new java.awt.Color(255, 255, 0));
        bt_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_5.setPreferredSize(new java.awt.Dimension(75, 75));
        bt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_5ActionPerformed(evt);
            }
        });

        bt_7.setBackground(new java.awt.Color(153, 51, 255));
        bt_7.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        bt_7.setForeground(new java.awt.Color(255, 255, 0));
        bt_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_7.setPreferredSize(new java.awt.Dimension(75, 75));
        bt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_7ActionPerformed(evt);
            }
        });

        bt_3.setBackground(new java.awt.Color(153, 51, 255));
        bt_3.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        bt_3.setForeground(new java.awt.Color(255, 255, 0));
        bt_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_3.setPreferredSize(new java.awt.Dimension(75, 75));
        bt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_3ActionPerformed(evt);
            }
        });

        bt_8.setBackground(new java.awt.Color(153, 51, 255));
        bt_8.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        bt_8.setForeground(new java.awt.Color(255, 255, 0));
        bt_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_8.setPreferredSize(new java.awt.Dimension(75, 75));
        bt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_8ActionPerformed(evt);
            }
        });

        bt_6.setBackground(new java.awt.Color(153, 51, 255));
        bt_6.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        bt_6.setForeground(new java.awt.Color(255, 255, 0));
        bt_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_6.setPreferredSize(new java.awt.Dimension(75, 75));
        bt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_6ActionPerformed(evt);
            }
        });

        bt_2.setBackground(new java.awt.Color(153, 51, 255));
        bt_2.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        bt_2.setForeground(new java.awt.Color(255, 255, 0));
        bt_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_2.setPreferredSize(new java.awt.Dimension(75, 75));
        bt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_2ActionPerformed(evt);
            }
        });

        bt_4.setBackground(new java.awt.Color(153, 51, 255));
        bt_4.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        bt_4.setForeground(new java.awt.Color(255, 255, 0));
        bt_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_4.setPreferredSize(new java.awt.Dimension(75, 75));
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });

        nomeJ1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        nomeJ1.setForeground(new java.awt.Color(255, 255, 0));
        nomeJ1.setText("Jogador 1");

        nomeJ2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        nomeJ2.setForeground(new java.awt.Color(255, 255, 0));
        nomeJ2.setText("Jogador 2");

        placarJ1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        placarJ1.setForeground(new java.awt.Color(255, 255, 0));
        placarJ1.setText("0");
        placarJ1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        placarJ2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        placarJ2.setForeground(new java.awt.Color(255, 255, 0));
        placarJ2.setText("0");
        placarJ2.setToolTipText("");
        placarJ2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setBackground(new java.awt.Color(153, 51, 255));
        jButton1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButton1.setText("Velha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabuleiroPainelLayout = new javax.swing.GroupLayout(tabuleiroPainel);
        tabuleiroPainel.setLayout(tabuleiroPainelLayout);
        tabuleiroPainelLayout.setHorizontalGroup(
            tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabuleiroPainelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblVelha)
                .addGap(18, 52, Short.MAX_VALUE)
                .addGroup(tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(placarJ2)
                    .addComponent(nomeJ2)
                    .addComponent(placarJ1)
                    .addComponent(nomeJ1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(tabuleiroPainelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabuleiroPainelLayout.createSequentialGroup()
                        .addComponent(bt_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabuleiroPainelLayout.createSequentialGroup()
                        .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabuleiroPainelLayout.createSequentialGroup()
                        .addComponent(bt_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabuleiroPainelLayout.setVerticalGroup(
            tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabuleiroPainelLayout.createSequentialGroup()
                .addGroup(tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabuleiroPainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVelha, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabuleiroPainelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(nomeJ1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placarJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeJ2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placarJ2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabuleiroPainelLayout.createSequentialGroup()
                        .addGroup(tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabuleiroPainelLayout.createSequentialGroup()
                        .addComponent(bt_0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(bt_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(bt_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabuleiroPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setText("Jogo Da Velha");

        jMenuBar1.setBackground(new java.awt.Color(153, 51, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogodavelhaframe/imagens/controller.png"))); // NOI18N
        jMenu1.setText("Opção");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogodavelhaframe/imagens/arrow_rotate_anticlockwise.png"))); // NOI18N
        jMenuItem1.setText("Reset");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogodavelhaframe/imagens/cross.png"))); // NOI18N
        jMenu2.setText("Sair");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabuleiroPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(JBu_02, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabuleiroPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBu_02, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void bt_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_0ActionPerformed
        jogada(bt_0, 0, 0);
    }//GEN-LAST:event_bt_0ActionPerformed

    private void bt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_2ActionPerformed
        jogada(bt_2, 0, 2);
    }//GEN-LAST:event_bt_2ActionPerformed

    private void bt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_5ActionPerformed
        jogada(bt_5, 1, 2);
    }//GEN-LAST:event_bt_5ActionPerformed

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
        jogada(bt_4, 1, 1);
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_7ActionPerformed
        jogada(bt_7, 2, 1);
    }//GEN-LAST:event_bt_7ActionPerformed

    private void bt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_8ActionPerformed
        jogada(bt_8, 2, 2);
    }//GEN-LAST:event_bt_8ActionPerformed

    private void bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1ActionPerformed
        jogada(bt_1, 0, 1);
    }//GEN-LAST:event_bt_1ActionPerformed

    private void bt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_3ActionPerformed
        jogada(bt_3, 1, 0);
    }//GEN-LAST:event_bt_3ActionPerformed

    private void bt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_6ActionPerformed
        jogada(bt_6, 2, 0);
    }//GEN-LAST:event_bt_6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        limpar();
        limparplacar();
        jogador1 = JOptionPane.showInputDialog("Digite o nome do primeiro jogador: ");
        jogador2 = JOptionPane.showInputDialog("Digite o nome do segundo jogador: ");
        nomeJ1.setText(jogador1);
        nomeJ2.setText(jogador2);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JBu_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBu_02ActionPerformed
        limpar();
        jogador1 = JOptionPane.showInputDialog("Digite o nome do primeiro jogador: ");
        jogador2 = JOptionPane.showInputDialog("Digite o nome do segundo jogador: ");
        nomeJ1.setText(jogador1);
        nomeJ2.setText(jogador2);
        tabuleiroPainel.setVisible(true);
        JBu_02.setVisible(false);
    }//GEN-LAST:event_JBu_02ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limparTabuleiro();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */;

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBu_02;
    private javax.swing.JButton bt_0;
    private javax.swing.JButton bt_1;
    private javax.swing.JButton bt_2;
    private javax.swing.JButton bt_3;
    private javax.swing.JButton bt_4;
    private javax.swing.JButton bt_5;
    private javax.swing.JButton bt_6;
    private javax.swing.JButton bt_7;
    private javax.swing.JButton bt_8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private transient javax.swing.JLabel lblVelha;
    private javax.swing.JLabel nomeJ1;
    private javax.swing.JLabel nomeJ2;
    private javax.swing.JLabel placarJ1;
    private javax.swing.JLabel placarJ2;
    private javax.swing.JPanel tabuleiroPainel;
    // End of variables declaration//GEN-END:variables
}
